// /** @jsxImportSource @emotion/react */

import Head from "next/head";
import { css } from "@emotion/react";
import Introduction from "./components/Introduction";
import { getData } from "@/util/function";
import useDataStore from "@/util/store";
import { useEffect } from "react";

export default function Home() {
  const { totalList, changeTotalList } = useDataStore();

  useEffect(() => {
    if (!totalList) {
      getData({ codename: "", title: "" }).then((res) => {
        changeTotalList(res);
      });
    }
  }, []);

  return (
    <>
      <Head>
        <title>서울, 오늘의 문화</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center items-center bg-sky-100">
        <Introduction />
      </div>
    </>
  );
}

const style = {
  // color: "red",
};
